version: 2
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run: cargo build
  test:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run: cargo test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
